### ISSUE TITLE
Error: Cannot find module '../demo-config'

### ISSUE THREAD

**Issue by brenopolanski** [keen/dashboard-builder#194]
When i run `npm start` I received this message on my terminal:

```
] internal/modules/cjs/loader.js:638
[0]     throw err;
[0]     ^
[0] 
[0] Error: Cannot find module '../demo-config'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at Object.<anonymous> (/home/brenopolanski/github/others/dashboard-builder/webpack.config.js:13:22)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

What info should have in `demo-config.js` ?

**Comment by dariuszlacheta** [comment]
Ola @brenopolanski ,
Tudo bom?

`demo-config.js` is holding a configuration object for dashboard builder, It should look like this:
const demoConfig = {
  projectId: 'YOUR_PROJECT_ID',
  readKey: 'YOUR_READ_KEY ',
  writeKey: ' YOUR_WRITE_KEY ',
  masterKey: 'YOUR_MASTER_KEY',
};

This is configured in webpack.config.js. `demo-config.js` is only needed when running app in developement mode.

**Comment by brenopolanski** [comment]
Thanks! I would like to run in development mode because i want contribute for the project :)
